# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ERP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for ERP
pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'RealmSwift'
end
